language: nix
nix: 2.1.1
sudo: require

install:
  - sudo cp -rT $TRAVIS_BUILD_DIR/nix /etc/nix

before_script:
  - git config --global user.email "travis-ci@example.com"
  - git config --global user.name "Travis-CI"

script:
  - nix-build travis.nix -A example
  - nix build -f ./release.nix testresults
